### ISSUE TITLE
Footer adjustments

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#15]
- [ ] #52 (Specifically, a mobile footer)
- [ ] #4 
- [ ] #2 (linked in footer)
- [ ] #3 (linked in footer)
