### ISSUE TITLE
Change "Team size" to "Lobby size" in all pages

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#211]
"Team size" should be changed to "Lobby size" here and everywhere else this label is used. The API will also be updating to use `lobbySize` instead.

![Image](https://github.com/user-attachments/assets/abc016a0-0879-43e8-b0cb-7d8ab0df0ef5)

# Tasks

-  [ ] Change "Team size" to "Lobby size" on the submission page
- [ ] Use `lobbySize` everywhere as needed for API calls
- [x] Use "format" on the tournaments page (done in #209)
