### ISSUE TITLE
Admin functionality

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-web#55]
# Dependencies:

- [x] https://github.com/osu-tournament-rating/otr-api/issues/371
- [x] Design finalized / approved by starlight
- [x] Specifics approved by Cytusine and SourMongoose

# Tasks:

- [x] #236
- [ ] Matches edit panel functionality
- [ ] Games edit panel functionality
- [ ] GameScores edit panel functionality
- [ ] Matches edit panel design implemented
- [ ] Games edit panel design implemented
- [ ] GameScores edit panel design implemented

**Comment by hburn7** [comment]
@myssto Isn't the admin panel going to be deleted in favor of browsing directly to the entity's webpage and making modifications there?
